# Set up Package

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option("display.precision", 4)

# Read Data

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/leonv1602/claim-reserving/main/data/wkcomp_pos.csv')
data.head()

GRCODE               GRNAME  AccidentYear  DevelopmentYear  DevelopmentLag  \
0      86  Allstate Ins Co Grp          1988             1988               1   
1      86  Allstate Ins Co Grp          1988             1989               2   
2      86  Allstate Ins Co Grp          1988             1990               3   
3      86  Allstate Ins Co Grp          1988             1991               4   
4      86  Allstate Ins Co Grp          1988             1992               5   

   IncurLoss_D  CumPaidLoss_D  BulkLoss_D  EarnedPremDIR_D  EarnedPremCeded_D  \
0       367404          70571      127737           400699               5957   
1       362988         155905       60173           400699               5957   
2       347288         220744       27763           400699               5957   
3       330648         251595       15280           400699               5957   
4       354690         274156       27689           400699               5957   

   EarnedPremNet_D  Single  PostedReserve97_D  
0           394742       0             281872  
1           394742       0             281872  
2           394742       0             281872  
3           394742       0             281872  
4           394742       0             281872

In [3]:
df = data[data['GRCODE'] == 337]
df = df[df['DevelopmentYear'] <= 1997]

In [4]:
tr_inc = pd.pivot_table(df, values='IncurLoss_D', index='AccidentYear',
                       columns=['DevelopmentLag'], aggfunc=np.sum)
tr_inc

DevelopmentLag       1        2        3        4        5        6        7   \
AccidentYear                                                                    
1988            62679.0  64000.0  65607.0  65292.0  62250.0  61185.0  59387.0   
1989            62058.0  56660.0  56598.0  56831.0  55294.0  53481.0  51379.0   
1990            63955.0  61523.0  63166.0  61402.0  59474.0  57613.0  57161.0   
1991            73918.0  75094.0  73188.0  71199.0  71056.0  70831.0  70532.0   
1992            77143.0  75133.0  73284.0  73155.0  68284.0  67845.0      NaN   
1993            79925.0  78263.0  78163.0  68546.0  67697.0      NaN      NaN   
1994            73628.0  73554.0  70736.0  69720.0      NaN      NaN      NaN   
1995            69521.0  80281.0  79381.0      NaN      NaN      NaN      NaN   
1996            69720.0  73181.0      NaN      NaN      NaN      NaN      NaN   
1997            50171.0      NaN      NaN      NaN      NaN      NaN      NaN   

DevelopmentLag       8        9        10  
AccidentYear                               
1988            57138.0  53473.0  53261.0  
1989            48446.0  48300.0      NaN  
1990            56971.0      NaN      NaN  
1991                NaN      NaN      NaN  
1992                NaN      NaN      NaN  
1993                NaN      NaN      NaN  
1994                NaN      NaN      NaN  
1995                NaN      NaN      NaN  
1996                NaN      NaN      NaN  
1997                NaN      NaN      NaN

In [5]:
tr_cum = tr_inc.cumsum(axis = 1)
tr_cum

DevelopmentLag       1         2         3         4         5         6   \
AccidentYear                                                                
1988            62679.0  126679.0  192286.0  257578.0  319828.0  381013.0   
1989            62058.0  118718.0  175316.0  232147.0  287441.0  340922.0   
1990            63955.0  125478.0  188644.0  250046.0  309520.0  367133.0   
1991            73918.0  149012.0  222200.0  293399.0  364455.0  435286.0   
1992            77143.0  152276.0  225560.0  298715.0  366999.0  434844.0   
1993            79925.0  158188.0  236351.0  304897.0  372594.0       NaN   
1994            73628.0  147182.0  217918.0  287638.0       NaN       NaN   
1995            69521.0  149802.0  229183.0       NaN       NaN       NaN   
1996            69720.0  142901.0       NaN       NaN       NaN       NaN   
1997            50171.0       NaN       NaN       NaN       NaN       NaN   

DevelopmentLag        7         8         9         10  
AccidentYear                                            
1988            440400.0  497538.0  551011.0  604272.0  
1989            392301.0  440747.0  489047.0       NaN  
1990            424294.0  481265.0       NaN       NaN  
1991            505818.0       NaN       NaN       NaN  
1992                 NaN       NaN       NaN       NaN  
1993                 NaN       NaN       NaN       NaN  
1994                 NaN       NaN       NaN       NaN  
1995                 NaN       NaN       NaN       NaN  
1996                 NaN       NaN       NaN       NaN  
1997                 NaN       NaN       NaN       NaN

In [6]:
link_ratio = tr_cum.div(tr_cum.shift(axis=1), axis=0).iloc[:, 1:]
link_ratio

DevelopmentLag      2       3       4       5       6       7       8   \
AccidentYear                                                             
1988            2.0211  1.5179  1.3396  1.2417  1.1913  1.1559  1.1297   
1989            1.9130  1.4767  1.3242  1.2382  1.1861  1.1507  1.1235   
1990            1.9620  1.5034  1.3255  1.2379  1.1861  1.1557  1.1343   
1991            2.0159  1.4912  1.3204  1.2422  1.1943  1.1620     NaN   
1992            1.9739  1.4813  1.3243  1.2286  1.1849     NaN     NaN   
1993            1.9792  1.4941  1.2900  1.2220     NaN     NaN     NaN   
1994            1.9990  1.4806  1.3199     NaN     NaN     NaN     NaN   
1995            2.1548  1.5299     NaN     NaN     NaN     NaN     NaN   
1996            2.0496     NaN     NaN     NaN     NaN     NaN     NaN   
1997               NaN     NaN     NaN     NaN     NaN     NaN     NaN   

DevelopmentLag      9       10  
AccidentYear                    
1988            1.1075  1.0967  
1989            1.1096     NaN  
1990               NaN     NaN  
1991               NaN     NaN  
1992               NaN     NaN  
1993               NaN     NaN  
1994               NaN     NaN  
1995               NaN     NaN  
1996               NaN     NaN  
1997               NaN     NaN

In [7]:
median_ldf = np.nanmedian(link_ratio, axis =0 )
median_ldf

array([1.99899495, 1.49263484, 1.32416323, 1.23801876, 1.1861366 ,
       1.15578085, 1.12974114, 1.10853094, 1.0966605 ])

In [8]:
median_ldf[1:][::-1]

array([1.0966605 , 1.10853094, 1.12974114, 1.15578085, 1.1861366 ,
       1.23801876, 1.32416323, 1.49263484])

In [37]:
np.cumprod(median_ldf[8:][::-1])[::-1].tolist()

[1.0966605022404272]

In [47]:
tr_cum.values[0, tr_cum.shape[1]-0-1]

604272.0

In [70]:
tr_fitted_c = [(np.cumprod(median_ldf[i:][::-1])[::-1]*tr_cum.values[i, tr_cum.shape[1]-i-1]) for i in range(tr_cum.shape[1])]
tr_fitted_c[-1] = tr_cum.iloc[-1, 0]
tr_fitted_c


[array([5565134.39874966, 2783966.21537376, 1865135.49576129,
        1408538.96270418, 1137736.36275181,  959195.05737414,
         829910.84375739,  734602.65465302,  662681.23500983]),
 array([2253108.41099685, 1509484.00520887, 1139953.12391372,
         920788.24601286,  776291.91030472,  671660.12723909,
         594525.68454288,  536318.52863917]),
 array([1485464.21870872, 1121813.52749395,  906136.12846491,
         763939.10240284,  660972.28106035,  585065.24643139,
         527784.31661074]),
 array([1179045.79566338,  952365.04675775,  802913.46534487,
         694693.52074509,  614913.88906201,  554710.62192225]),
 array([818733.66782583, 690252.42858978, 597217.39703782, 528632.06761183,
        476876.23943624]),
 array([591439.48951343, 511722.86804443, 452955.85681247, 408609.12317177]),
 array([395043.78041129, 349676.36822339, 315441.23354343]),
 array([278613.67099807, 251335.94388497]),
 array([156713.88243066]),
 50171.0]

In [75]:
copy_fitted = tr_cum.copy()
copy_fitted.apply(lambda x : tr_fitted_c[x.name-1].flatten(), axis = 0,)

DevelopmentLag
1     [5565134.398749663, 2783966.215373756, 1865135...
2     [2253108.410996851, 1509484.0052088653, 113995...
3     [1485464.2187087224, 1121813.5274939516, 90613...
4     [1179045.795663378, 952365.0467577452, 802913....
5     [818733.6678258287, 690252.4285897766, 597217....
6     [591439.489513433, 511722.8680444253, 452955.8...
7     [395043.78041128523, 349676.36822339206, 31544...
8              [278613.67099806585, 251335.94388496783]
9                                   [156713.8824306593]
10                                            [50171.0]
dtype: object